#!/bin/bash

rm -rf testdir
mkdir testdir
echo "# The initial copy of this file has been generated by /vobs/ims_ttcn3/projects/TAS/tools/tiger/src/autoGenerateConfigFiles.pl
# it should be editted to include your test cases

[INCLUDE]
"/home/ealekry/config/base.cfg"
"/vobs/ims_ttcn3/projects/TAS/imsas_ttcn/testobjects/testAutomationSupport/testAutomation.cfg"
"/vobs/ims_ttcn3/projects/TAS/imsas_ttcn/testobjects/testAutomationSupport/licenses_tsp.cfg"

[MAIN_CONTROLLER]
#TCPPort := 9011
#NumHCs := 1

[LOGGING]
FileMask := LOG_ALL|MATCHING|USER
MatchingHints := Detailed

[EXECUTE]">testdir/titan.cfg


for i in {1..100}; do 
echo -e "TC_MMTCG_TCs.TC_MMTCG_NCBP00$i">>testdir/titan.cfg; 
echo -e "TC_MMTCG_TCs.TC_MMTCG_NCBP00$i">>testdir/titan_user.cfg;
for j in {1..3}; do
random=$[1 + $[ RANDOM % 3 ]];
	if [ "$random" -eq 1 ]
	then
		touch testdir/TC_MMTCG_NCBP00${i}-29999999_999999-999s-pass-ealekry.tgz;
	fi
	if [ "$random" -eq 2 ]
	then
		touch testdir/TC_MMTCG_NCBP00${i}-29999999_999999-999s-fail-ealekry.tgz;
	fi
	if [ "$random" -eq 3 ]
	then
		touch testdir/TC_MMTCG_NCBP00${i}-29999999_999999-999s-error-ealekry.tgz;
	fi

done
done

echo "Script without parameters"

./TC_statistics.rb
echo "Script with both parameters"
./TC_statistics.rb ~/GIT/testdir ~/GIT/testdir/titan_user.cfg;
mv report.txt report_user.txt
echo "Script with first parameter"
./TC_statistics.rb ~/GIT/testdir;
echo "Diff between report and report_user"
diff report.txt report_user.txt

rm -rf stats.txt;
./TC_statistics.bash  ~/GIT/testdir  ~/GIT/testdir/titan_user.cfg;
#echo "Diff between report and stats"
#diff report.txt stats.txt

#cat report.txt
