#!/bin/bash

rm -rf testdir
mkdir testdir
echo "# The initial copy of this file has been generated by /vobs/ims_ttcn3/projects/TAS/tools/tiger/src/autoGenerateConfigFiles.pl
# it should be editted to include your test cases

[INCLUDE]
"/home/ealekry/config/base.cfg"
"/vobs/ims_ttcn3/projects/TAS/imsas_ttcn/testobjects/testAutomationSupport/testAutomation.cfg"
"/vobs/ims_ttcn3/projects/TAS/imsas_ttcn/testobjects/testAutomationSupport/licenses_tsp.cfg"

[MAIN_CONTROLLER]
#TCPPort := 9011
#NumHCs := 1

[LOGGING]
FileMask := LOG_ALL|MATCHING|USER
MatchingHints := Detailed

[EXECUTE]">testdir/titan.cfg
